- hosts: localhost
  sudo: yes
  roles:
   - role: ossec-role
     ossec_version: "2.8.2"
     ossec_preloaded_vars: |
       USER_LANGUAGE="en"
       USER_NO_STOP="y"
       USER_INSTALL_TYPE="local"
       USER_ENABLE_EMAIL="n"
       USER_DIR="{{ ossec_dir }}"
       USER_UPDATE="n"
       USER_DELETE_DIR="y"
       USER_ENABLE_ACTIVE_RESPONSE="n"
       USER_ENABLE_SYSCHECK="y"
       USER_ENABLE_ROOTCHECK="y"
       USER_ENABLE_FIREWALL_RESPONSE="n"
       #### exit ? ###
       tags: ossec-role
